spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: your own username
    password: your own password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true